# SPDX-License-Identifier: GPL-2.0
# NUC990 series audio

snd-soc-nuc990-i2s-objs := nuc990-i2s.o

obj-$(CONFIG_SND_SOC_NUC990) += snd-soc-nuc990-i2s.o 
# obj-$(CONFIG_SND_SOC_NUC990) += snd-soc-nuc990-i2s.o

# Boards
snd-soc-nuc990-audio-objs := nuc990-audio.o

obj-$(CONFIG_SND_SOC_NUC990EVB) += snd-soc-nuc990-audio.o
