# SPDX-License-Identifier: GPL-2.0-only

ifeq ($(CONFIG_CRYPTO_DEV_NUVOTON_NUC990),y)
	obj-y += nuc990-crypto.o
	obj-y += nuc990-aes.o
	obj-y += nuc990-prng.o
	obj-y += nuc990-sha.o
	obj-y += nuc990-ecc.o
	obj-y += nuc990-rsa.o
endif
